# Site settings
title: KunLin Lee Blog
email: 
description: ""
baseurl: ""
url: "http://LeeKLTW.github.io"
twitter_username:
github_username: LeeKLTW

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
